spring:
  jwt:
    secret: HelloMyNickNameIsBeHangAndNiceToMeetYouHowAreYouImFineThankYouAndYou

codef:
  sand-client-id: ef27cfaa-10c1-4470-adac-60ba476273f9
  sand-client-secret: 83160c33-9045-4915-86d8-809473cdf5c3
  demo-client-id: b6071877-4d32-4ef1-b19d-157a401ff4b0
  demo-client-secret: 4f537d88-e2f3-4a54-b36f-f4cf81484215
  api-client-id: 1aa2fc52-4896-4123-814f-789f117156be
  api-client-secret: de4e74a1-f978-405b-a368-a73673276963
  public-key: MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAx1ohEpXp9O0eqAG4OQuNnyj2RvqTMqsLW3ZYmZxePiujf2HsW4VXQ4T1/S0tIP5NgGgY2azeOs4pPGVnFg9B8j3aqFJR0hgHtGO1DiuaOLLSvJe7k/89MahdozXk/D7H6g6APg6g7T7ZabGJwG1ED2FzVH/HtqdfJ/g4XGmSlconTS8K0U2kFgxkK1jjhdaZxCgZ5c7cYiDyQ5EgEHDNdAQSi/OIkDdZF6kXezg5xVo2Q5uvsZQHhb9JHaO1cXfYjDH1EuYdf7KwPYpLfvLE8M1glPDKlZ0Yea5RwBsRbjNUJQVaK1CMXq94+vdLHMMKhbd9IwCe4bRLcaCV8wDRfwIDAQAB
kg:
  mid: gasomanpb1

