spring:
  jwt:
    secret: HelloMyNickNameIsBeHangAndNiceToMeetYouHowAreYouImFineThankYouAndYou

codef:
  client-id: b6071877-4d32-4ef1-b19d-157a401ff4b0
  client-secret: 4f537d88-e2f3-4a54-b36f-f4cf81484215
  public-key: MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAx1ohEpXp9O0eqAG4OQuNnyj2RvqTMqsLW3ZYmZxePiujf2HsW4VXQ4T1/S0tIP5NgGgY2azeOs4pPGVnFg9B8j3aqFJR0hgHtGO1DiuaOLLSvJe7k/89MahdozXk/D7H6g6APg6g7T7ZabGJwG1ED2FzVH/HtqdfJ/g4XGmSlconTS8K0U2kFgxkK1jjhdaZxCgZ5c7cYiDyQ5EgEHDNdAQSi/OIkDdZF6kXezg5xVo2Q5uvsZQHhb9JHaO1cXfYjDH1EuYdf7KwPYpLfvLE8M1glPDKlZ0Yea5RwBsRbjNUJQVaK1CMXq94+vdLHMMKhbd9IwCe4bRLcaCV8wDRfwIDAQAB


