spring:
  datasource:  # mysql 사용
    url: jdbc:mysql://localhost:3306/dabom_test?validationQuery="select 1"&useSSL=false&allowPublicKeyRetrieval=true&characterEncoding=UTF-8&serverTimezone=UTC&useLegacyDatetimeCode=false
    username: test
    password: test
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      connection-test-query: select 1 from dual

  jpa: # jpa 사용시 추가
    database: mysql
    database-platform: org.hibernate.dialect.MySQL8Dialect
    properties:
      hibernate:
        jdbc:
          time_zone: Asia/Seoul
        enable_lazy_load_no_trans: true
        format_sql: true
        hbm2ddl:
          auto: create
    show-sql: true

  data:
    redis:
      host: localhost
      port: 6379
path:
  resources: E:\ROOM\Github\dabom\dabom-backend\src\test\resources
  images: E:\ROOM\Github\dabom\dabom-backend\src\test\resources\images
